### ISSUE TITLE
Remove all remnants of Node.js backend and completely transition to Flask

### ISSUE THREAD

**Issue by nshdesai** [nshdesai/ComputingBlog#7]
The current project was initially created in Node.js and was transitioned into Flask. However, _both_ of these framework are used in the project currently (this is bad). Clean up all the parts of Node that are not used by the site and for the parts of the website that _do_ use Node: Switch to a Flask alternative.

**Comment by nshdesai** [comment]
Issue should be fixed after #22 . @Henry-Zhuo  please ensure that the transition is complete.

**Comment by DerpsBurps** [comment]
Seems to be cleaned up nicely after #22. Merged.
